name: Build and Release

on:
  push:
    tags:
      - "v*" # Every time a tag (v1.x.x or so) is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build project (Release x64)
        run: msbuild satisfactory-external-bhop-cheat.sln /p:Configuration=Release /p:Platform=x64

      - name: Prepare release package
        run: |
          mkdir package
          copy x64\Release\satisfactory-external-bhop-cheat.exe package\
          copy config.ini package\
          powershell Compress-Archive -Path package\* -DestinationPath release.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
