name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build project
        run: msbuild satisfactory-external-bhop-cheat.sln /p:Configuration=Release /p:Platform=x64

      - name: Copy config.ini to build output
        run: |
          copy config.ini x64\Release\config.ini

      - name: Create ZIP package
        run: |
          powershell Compress-Archive -Path x64\Release\satisfactory-external-bhop-cheat.exe, x64\Release\config.ini -DestinationPath release.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
